import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { heroImageUrl, itemImageUrl, mapHeroFeed, mapItemFeed } from '../src/lib/dota-feed';

const FEED = 'https://www.dota2.com/datafeed';
const HEADER = '# Generated by scripts/fetch-dota-assets.ts — do not edit by hand\n';

async function getJson(path: string) {
  const res = await fetch(`${FEED}/${path}`);
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return res.json();
}

async function downloadWebp(src: string, dest: string, width: number): Promise<boolean> {
  if (existsSync(dest)) return false;
  const res = await fetch(src);
  if (!res.ok) {
    console.warn(`skip ${src}: HTTP ${res.status}`);
    return false;
  }
  const tmp = `${dest}.png`;
  writeFileSync(tmp, Buffer.from(await res.arrayBuffer()));
  execFileSync('cwebp', ['-quiet', '-q', '80', '-resize', String(width), '0', tmp, '-o', dest]);
  rmSync(tmp);
  return true;
}

const heroes = mapHeroFeed(await getJson('herolist?language=schinese'));
const items = mapItemFeed(await getJson('itemlist?language=schinese'));
writeFileSync('src/data/heroes.yaml', HEADER + stringify(heroes));
writeFileSync('src/data/items.yaml', HEADER + stringify(items));

mkdirSync('public/img/heroes', { recursive: true });
mkdirSync('public/img/items', { recursive: true });
let fetched = 0;
for (const h of heroes) if (await downloadWebp(heroImageUrl(h.id), `public/img/heroes/${h.id}.webp`, 256)) fetched++;
for (const i of items) if (await downloadWebp(itemImageUrl(i.id), `public/img/items/${i.id}.webp`, 88)) fetched++;
console.log(`${heroes.length} heroes, ${items.length} items, ${fetched} new images`);
