import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { stringify } from 'yaml';
import { heroImageUrl, itemImageUrl, mapAbilityFeed, mapHeroFeed, mapItemFeed } from '../src/lib/dota-feed';

const FEED = 'https://www.dota2.com/datafeed';
const HEADER = '# Generated by scripts/fetch-dota-assets.ts — do not edit by hand\n';

async function getJson(path: string) {
  const res = await fetch(`${FEED}/${path}`, { signal: AbortSignal.timeout(30_000) });
  if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
  return res.json();
}

let failed = 0;

// Returns true when a new image was written. Output is written to a temp file and renamed
// so an interrupted run never leaves a truncated .webp that existsSync would later skip.
// `thumb` also writes a smaller copy from the same source PNG (hero grid thumbnails, see tools/hero-thumbs.ts).
async function downloadWebp(
  src: string,
  dest: string,
  width: number,
  thumb?: { dest: string; width: number; quality: number },
): Promise<boolean> {
  if (existsSync(dest) && (!thumb || existsSync(thumb.dest))) return false;
  const res = await fetch(src, { signal: AbortSignal.timeout(30_000) });
  if (!res.ok) {
    console.log(`::warning::skip ${src}: HTTP ${res.status}`);
    failed++;
    return false;
  }
  const png = `${dest}.png`;
  const tmp = `${dest}.tmp`;
  try {
    writeFileSync(png, Buffer.from(await res.arrayBuffer()));
    if (!existsSync(dest)) {
      execFileSync('cwebp', ['-quiet', '-q', '80', '-resize', String(width), '0', png, '-o', tmp]);
      renameSync(tmp, dest);
    }
    if (thumb && !existsSync(thumb.dest)) {
      execFileSync('cwebp', ['-quiet', '-q', String(thumb.quality), '-resize', String(thumb.width), '0', png, '-o', tmp]);
      renameSync(tmp, thumb.dest);
    }
    return true;
  } finally {
    rmSync(png, { force: true });
    rmSync(tmp, { force: true });
  }
}

const heroes = mapHeroFeed(await getJson('herolist?language=schinese'));
const items = mapItemFeed(await getJson('itemlist?language=schinese'));
const abilityFeed = await getJson('abilitylist?language=schinese');
const rawAbilities: unknown = abilityFeed?.result?.data?.itemabilities;
if (!Array.isArray(rawAbilities)) {
  throw new Error(`abilitylist: unexpected shape, top-level keys ${JSON.stringify(Object.keys(abilityFeed ?? {}))}`);
}
console.log(`abilitylist: ${rawAbilities.length} rows, sample ${JSON.stringify(rawAbilities.slice(0, 2))}`);
const heroAbilities = mapAbilityFeed(abilityFeed, heroes.map((h) => h.id));
writeFileSync('src/data/heroes.yaml', HEADER + stringify(heroes));
writeFileSync('src/data/hero-abilities.yaml', HEADER + stringify(heroAbilities));
writeFileSync('src/data/items.yaml', HEADER + stringify(items));

mkdirSync('public/img/heroes/thumb', { recursive: true });
mkdirSync('public/img/items', { recursive: true });
let fetched = 0;
for (const h of heroes) {
  const thumb = { dest: `public/img/heroes/thumb/${h.id}.webp`, width: 128, quality: 70 };
  if (await downloadWebp(heroImageUrl(h.id), `public/img/heroes/${h.id}.webp`, 256, thumb)) fetched++;
}
for (const i of items) if (await downloadWebp(itemImageUrl(i.id), `public/img/items/${i.id}.webp`, 88)) fetched++;
console.log(`${heroAbilities.length} heroes with abilities (${heroAbilities.reduce((n, h) => n + h.abilities.length, 0)} abilities)`);
console.log(`${heroes.length} heroes, ${items.length} items, ${fetched} new images, ${failed} failed downloads`);
