// Import community research (quality, values, tips, recommended heroes) into src/data/blessings.community.yaml.
// Usage: npm run community -- <blessing-notes.json>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { Document, isMap, isSeq, visit } from 'yaml';
import { z } from 'astro/zod';
import { COMMUNITY_FILE, GENERATED_FILE, loadBlessingFiles } from '../src/lib/blessings';
import { convertNote, type ResearchNote, type Skip } from '../src/lib/community';
import { parseWith, readYaml } from '../src/lib/data-file';
import { generatedBlessingSchema, heroSchema, type BlessingCommunity } from '../src/lib/schema';
import { placeholderKeys } from '../src/lib/template';

const HEADER = [
  ' Generated by scripts/import-community.ts — do not edit by hand; put corrections in blessings.overrides.yaml.',
  ' Source: community research (docs/research/community-sources.md), mainly the community wiki',
  ' http://122.51.0.76:8081 (web version of the Tencent doc attached to Bilibili video BV1feAHzJEGH),',
  ' the Steam workshop changelog and Bilibili comments. Tips are paraphrased; the wiki prose is not included.',
].join('\n');

const REASONS: Record<Skip['reason'], string> = {
  quality_conflict: '品质来源冲突，未写入品质（记为 quality_conflict）',
  unit_mismatch: '数值单位与模板不一致',
  not_placeholder: '数值键不是模板里的占位符',
  tip_too_long: '心得超过 80 字，疑似照抄',
  hero_unmapped: '英雄名对不上 heroes.yaml',
};

const file = process.argv[2];
if (!file) {
  console.error('用法：npm run community -- <blessing-notes.json>');
  process.exit(1);
}

try {
  const root = process.cwd();
  const notes = JSON.parse(readFileSync(file, 'utf8')) as ResearchNote[];
  if (!Array.isArray(notes)) throw new Error(`${file}：应为数组`);
  const generated = parseWith(z.array(generatedBlessingSchema), readYaml(root, GENERATED_FILE, []), GENERATED_FILE);
  const heroes = parseWith(z.array(heroSchema), readYaml(root, 'src/data/heroes.yaml', []), 'heroes.yaml');
  const heroIdByName = new Map(heroes.map((h) => [h.name, h.id]));
  const byId = new Map(notes.map((n) => [n.id, n]));

  const out: Record<string, BlessingCommunity> = {};
  const skipped: Skip[] = [];
  const unmapped = new Map<string, number>();
  const unknownIds = notes.filter((n) => !generated.some((g) => g.id === n.id)).map((n) => n.id);
  for (const g of generated) {
    const note = byId.get(g.id);
    if (!note) continue;
    const placeholders = new Set([...placeholderKeys(g.effect), ...placeholderKeys(g.summary)]);
    const r = convertNote(note, { heroIdByName, placeholders });
    skipped.push(...r.skipped);
    for (const name of r.unmapped) unmapped.set(name, (unmapped.get(name) ?? 0) + 1);
    if (r.entry) out[g.id] = r.entry;
  }

  const doc = new Document(out);
  doc.commentBefore = HEADER;
  // Compact one-line maps for values, tips and hero picks.
  visit(doc, {
    Pair(_, pair) {
      const key = String((pair.key as { value?: unknown })?.value ?? '');
      if (['numbers', 'number_sources', 'change_summary'].includes(key) && isMap(pair.value)) pair.value.flow = true;
      if (['tips', 'wiki_notes', 'changes', 'recommended_heroes', 'quality_conflict'].includes(key) && isSeq(pair.value)) {
        for (const item of pair.value.items) if (isMap(item)) item.flow = true;
      }
    },
  });
  writeFileSync(join(root, COMMUNITY_FILE), doc.toString({ lineWidth: 0 }));
  // Re-read through the real schema and merge, so a bad file fails here instead of in the build.
  const merged = loadBlessingFiles(root);

  const entries = Object.values(out);
  const count = (f: (e: BlessingCommunity) => number) => entries.reduce((n, e) => n + f(e), 0);
  const qualities = entries.filter((e) => e.quality);
  const dist = ['ssr', 'sr', 'r'].map((q) => `${q} ${qualities.filter((e) => e.quality === q).length}`).join(' / ');
  console.log(`✓ ${COMMUNITY_FILE}：${entries.length} 个福佑（输入 ${notes.length} 条）`);
  console.log(`  品质 ${qualities.length}（${dist}）`);
  console.log(`  数值 ${count((e) => Object.keys(e.numbers ?? {}).length)} 项，覆盖 ${entries.filter((e) => e.numbers).length} 个福佑`);
  console.log(`  心得 ${count((e) => e.tips?.length ?? 0)} 条，覆盖 ${entries.filter((e) => e.tips).length} 个福佑`);
  console.log(`  图鉴备注 ${count((e) => e.wiki_notes?.length ?? 0)} 条，覆盖 ${entries.filter((e) => e.wiki_notes).length} 个福佑`);
  console.log(`  官方改动 ${count((e) => e.changes?.length ?? 0)} 条，覆盖 ${entries.filter((e) => e.changes).length} 个福佑；平衡统计 ${entries.filter((e) => e.change_summary).length} 条`);
  console.log(`  推荐英雄 ${count((e) => e.recommended_heroes?.length ?? 0)} 个，覆盖 ${entries.filter((e) => e.recommended_heroes).length} 个福佑`);
  console.log(`  品质备注 ${entries.filter((e) => e.notes).length} 条`);
  const manualWins = merged.filter((b) => b.quality_source === 'manual' && out[b.id]?.quality).length;
  if (manualWins > 0) console.log(`  其中 ${manualWins} 个品质被 overrides 的人工标注覆盖`);
  for (const [reason, label] of Object.entries(REASONS)) {
    const list = skipped.filter((s) => s.reason === reason);
    if (list.length === 0) continue;
    console.log(`  跳过 · ${label}：${list.length}`);
    for (const s of list) console.log(`    - ${s.id} ${s.what}`);
  }
  if (unmapped.size > 0) {
    console.log(`  未对应的英雄名：${[...unmapped].map(([n, c]) => `${n}（${c}）`).join('、')}`);
  }
  if (unknownIds.length > 0) console.log(`  未知福佑 id（已跳过）：${unknownIds.join(', ')}`);
} catch (e) {
  console.error(e instanceof Error ? e.message : e);
  process.exit(1);
}
