// Import blessing text and icons from the workshop VPK.
// Usage: npx tsx scripts/import-vpk.ts <file.vpk> [--version YYYY-MM-DD --title 标题]
import { execFile } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { availableParallelism, tmpdir } from 'node:os';
import { join } from 'node:path';
import { parseArgs, promisify } from 'node:util';
import { Document, isScalar, isSeq, parse, parseDocument, visit, YAMLSeq, type Scalar } from 'yaml';
import { z } from 'astro/zod';
import {
  buildGenerated,
  diffGenerated,
  isEmptyDiff,
  versionEntryFromDiff,
  DIFF_FIELDS,
  type GeneratedDiff,
} from '../src/lib/bless-import';
import { GENERATED_FILE, OVERRIDES_FILE } from '../src/lib/blessings';
import { parseCsv } from '../src/lib/csv';
import { parseWith, readYaml } from '../src/lib/data-file';
import { writeBlessingColors } from '../tools/blessing-colors';
import { generatedBlessingSchema, versionSchema, type GeneratedBlessing } from '../src/lib/schema';
import { readVpkEntries, readVpkFile, type VpkEntry } from '../src/lib/vpk';

const ROOT = process.cwd();
const VERSIONS_FILE = 'src/data/versions.yaml';
const ICON_DIR = 'public/img/blessings';
const ICON_SRC_DIR = 'resource/flash3/images/spellicons/buff/bless/';
const CSV = {
  names: 'resource/bless_name.csv',
  desc: 'resource/bless_desc.csv',
  short: 'resource/bless_desc_short.csv',
} as const;
const HEADER = '# Generated by scripts/import-vpk.ts — do not edit by hand\n';
// Keys whose values are ids and must stay strings in YAML (10010 would otherwise become a number).
const ID_KEYS = new Set(['id', 'blessing']);
const PREVIEW_LINES = 20;

const execFileAsync = promisify(execFile);
const utf8 = new TextDecoder('utf-8');

function parseCli() {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: { version: { type: 'string' }, title: { type: 'string' } },
  });
  if (positionals.length !== 1)
    throw new Error('用法：tsx scripts/import-vpk.ts <file.vpk> [--version YYYY-MM-DD --title 标题]');
  const { version, title } = values;
  if ((version === undefined) !== (title === undefined)) throw new Error('--version 和 --title 必须同时提供');
  if (version !== undefined && !/^\d{4}-\d{2}-\d{2}$/.test(version)) {
    throw new Error(`--version 应为 YYYY-MM-DD，收到 "${version}"`);
  }
  if (title !== undefined && !title.trim()) throw new Error('--title 不能为空');
  return { vpkPath: positionals[0], version, title: title?.trim() };
}

/** Force double quotes on id-like scalars so they are never re-read as numbers or dates. */
function quoteIds(doc: Document): void {
  visit(doc, {
    Pair(_, pair) {
      if (isScalar(pair.key) && ID_KEYS.has(String(pair.key.value)) && isScalar(pair.value)) {
        if (typeof pair.value.value === 'string') (pair.value as Scalar).type = 'QUOTE_DOUBLE';
      }
    },
  });
}

function readVpkText(buf: Uint8Array, entries: Map<string, VpkEntry>, path: string): string {
  const entry = entries.get(path);
  if (!entry) throw new Error(`VPK 中缺少 ${path}`);
  return utf8.decode(readVpkFile(buf, entry));
}

function formatDiff(diff: GeneratedDiff): string[] {
  return [
    ...diff.added.map((b) => `  + ${b.id} ${b.name}`),
    ...diff.changed.map((c) => `  ~ ${c.id} ${c.name}：${c.fields.map((f) => DIFF_FIELDS[f]).join('、')}`),
    ...diff.removed.map((b) => `  - ${b.id} ${b.name}`),
  ];
}

/** Run `fn` over `items` with at most `limit` in flight. */
async function pool<T>(items: T[], limit: number, fn: (item: T) => Promise<void>): Promise<void> {
  let next = 0;
  const worker = async () => {
    while (next < items.length) await fn(items[next++]);
  };
  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, worker));
}

/** Convert every referenced icon to webp and delete webp files no longer referenced. */
async function writeIcons(buf: Uint8Array, entries: Map<string, VpkEntry>, blessings: GeneratedBlessing[]) {
  const dir = join(ROOT, ICON_DIR);
  mkdirSync(dir, { recursive: true });
  const wanted = [...new Set(blessings.flatMap((b) => (b.icon ? [b.icon] : [])))];
  const tmp = mkdtempSync(join(tmpdir(), 'fuyou-icons-'));
  try {
    await pool(wanted, availableParallelism(), async (file) => {
      const id = file.replace(/\.webp$/, '');
      const entry = entries.get(`${ICON_SRC_DIR}${id}.png`);
      if (!entry) throw new Error(`VPK 中缺少图标 ${id}.png`);
      const png = join(tmp, `${id}.png`);
      const dest = join(dir, file);
      writeFileSync(png, readVpkFile(buf, entry));
      try {
        await execFileAsync('cwebp', ['-quiet', '-q', '75', '-resize', '96', '0', png, '-o', `${dest}.tmp`]);
        renameSync(`${dest}.tmp`, dest);
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code === 'ENOENT')
          throw new Error('找不到 cwebp，请先安装（brew install webp）');
        throw new Error(`转换图标 ${id}.png 失败：${e instanceof Error ? e.message : e}`);
      } finally {
        rmSync(`${dest}.tmp`, { force: true });
      }
    });
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }

  const keep = new Set(wanted);
  const removed = readdirSync(dir).filter((f) => f.endsWith('.webp') && !keep.has(f));
  for (const f of removed) rmSync(join(dir, f));
  return { written: wanted.length, removed };
}

function writeGenerated(blessings: GeneratedBlessing[]): void {
  const doc = new Document(blessings);
  quoteIds(doc);
  writeFileSync(join(ROOT, GENERATED_FILE), HEADER + doc.toString({ lineWidth: 0 }));
  // Round-trip check: the file must re-read to exactly what we wrote.
  const back = parseWith(z.array(generatedBlessingSchema), readYaml(ROOT, GENERATED_FILE, []), GENERATED_FILE);
  if (JSON.stringify(back) !== JSON.stringify(blessings)) throw new Error(`${GENERATED_FILE} 回读结果与写入内容不一致`);
}

/** Prepend a version entry to versions.yaml, keeping its comments and existing formatting. */
function prependVersion(diff: GeneratedDiff, id: string, title: string): number {
  const path = join(ROOT, VERSIONS_FILE);
  const doc = existsSync(path) ? parseDocument(readFileSync(path, 'utf8')) : new Document([]);
  if (doc.errors.length > 0) throw new Error(`${VERSIONS_FILE} 解析失败：${doc.errors[0].message}`);
  const existing = z.array(versionSchema).parse(doc.toJS() ?? []);
  if (existing.some((v) => v.id === id)) throw new Error(`${VERSIONS_FILE} 已有版本 ${id}`);

  const entry = versionEntryFromDiff(diff, id, title);
  if (!isSeq(doc.contents)) doc.contents = new YAMLSeq();
  const seq = doc.contents as YAMLSeq;
  seq.flow = false; // "[]" placeholder becomes a block list
  seq.items.unshift(doc.createNode(entry));
  quoteIds(doc);
  writeFileSync(path, doc.toString({ lineWidth: 0 }));
  z.array(versionSchema).parse(parse(readFileSync(path, 'utf8')));
  return entry.changes.length;
}

function dirSize(dir: string): number {
  if (!existsSync(dir)) return 0;
  return readdirSync(dir).reduce((sum, f) => sum + statSync(join(dir, f)).size, 0);
}

async function main() {
  const { vpkPath, version, title } = parseCli();
  if (!existsSync(vpkPath)) throw new Error(`找不到文件：${vpkPath}`);
  const buf = new Uint8Array(readFileSync(vpkPath));
  const entries = readVpkEntries(buf);

  const iconIds = new Set<string>();
  for (const path of entries.keys()) {
    if (!path.startsWith(ICON_SRC_DIR) || !path.endsWith('.png')) continue;
    const name = path.slice(ICON_SRC_DIR.length, -'.png'.length);
    if (!name.includes('/')) iconIds.add(name);
  }

  const { blessings, skipped } = buildGenerated({
    names: parseCsv(readVpkText(buf, entries, CSV.names)),
    desc: parseCsv(readVpkText(buf, entries, CSV.desc)),
    short: parseCsv(readVpkText(buf, entries, CSV.short)),
    iconIds,
  });
  if (blessings.length === 0) throw new Error('没有解析出任何福佑，已中止');

  const prev = parseWith(
    z.array(generatedBlessingSchema),
    readYaml(ROOT, GENERATED_FILE, [], { optional: true }),
    GENERATED_FILE,
  );
  const diff = diffGenerated(prev, blessings);

  const icons = await writeIcons(buf, entries, blessings);
  writeGenerated(blessings);
  // Placeholder colors follow the icons; ImageMagick is optional for an import.
  try {
    console.log(`  图标颜色 ${writeBlessingColors(ROOT)} 个`);
  } catch (e) {
    console.log(`  ⚠ 未更新图标颜色：${e instanceof Error ? e.message : e}（之后运行 npm run icon-colors）`);
  }

  const withIcon = blessings.filter((b) => b.icon).length;
  const variantIcons = blessings.filter((b) => b.icon && b.icon !== `${b.id}.webp`).length;
  console.log(`✓ ${blessings.length} 个福佑写入 ${GENERATED_FILE}`);
  console.log(`  跳过 ${skipped.length} 个：${skipped.join(', ') || '无'}`);
  console.log(
    `  有图标 ${withIcon}（其中 ${variantIcons} 个使用基础 id 的图标），无图标 ${blessings.length - withIcon}`,
  );
  console.log(
    `  图标 ${icons.written} 个写入 ${ICON_DIR}（共 ${(dirSize(join(ROOT, ICON_DIR)) / 1024).toFixed(1)} KB），删除 ${icons.removed.length} 个旧图标`,
  );

  console.log(`\n变化：新增 ${diff.added.length}，移除 ${diff.removed.length}，变更 ${diff.changed.length}`);
  const lines = formatDiff(diff);
  for (const line of lines.slice(0, PREVIEW_LINES)) console.log(line);
  if (lines.length > PREVIEW_LINES) console.log(`  …… 另有 ${lines.length - PREVIEW_LINES} 条`);

  if (version && title) {
    if (isEmptyDiff(diff)) console.log(`\n无变化，未写入 ${VERSIONS_FILE}`);
    else console.log(`\n✓ ${VERSIONS_FILE} 新增版本 ${version}（${prependVersion(diff, version, title)} 条变更）`);
  }

  const overrides = readYaml(ROOT, OVERRIDES_FILE, {}, { optional: true });
  const known = new Set(blessings.map((b) => b.id));
  const orphans = Object.keys(overrides && typeof overrides === 'object' ? overrides : {}).filter(
    (id) => !known.has(id),
  );
  if (orphans.length > 0) {
    console.warn(`\n⚠ ${OVERRIDES_FILE} 中以下 id 已不存在，请手动处理：${orphans.join(', ')}`);
  }
}

try {
  await main();
} catch (e) {
  console.error(`✗ 导入失败：${e instanceof Error ? e.message : e}`);
  process.exit(1);
}
