// Average color of every blessing icon -> src/data/blessing-colors.yaml (keyed by icon file name
// without .webp). Painted inside the icon box until the image arrives.
// Usage: npm run icon-colors   (also run by scripts/import-vpk.ts after it writes icons)
import { execFileSync } from 'node:child_process';
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { stringify } from 'yaml';

export const BLESSING_COLORS_FILE = 'src/data/blessing-colors.yaml';
const ICON_DIR = 'public/img/blessings';

function imageMagick(): string {
  for (const bin of ['magick', 'convert']) {
    try {
      execFileSync(bin, ['-version'], { stdio: 'ignore' });
      return bin;
    } catch {
      // try the next name
    }
  }
  throw new Error('需要 ImageMagick（magick 或 convert）');
}

/** Returns the number of colors written. */
export function writeBlessingColors(root = process.cwd()): number {
  const im = imageMagick();
  const colors: Record<string, string> = {};
  for (const file of readdirSync(join(root, ICON_DIR)).filter((f) => f.endsWith('.webp')).sort()) {
    const hex = execFileSync(im, [join(root, ICON_DIR, file), '-scale', '1x1!', '-format', '%[hex:u.p{0,0}]', 'info:'])
      .toString()
      .trim();
    colors[file.replace(/\.webp$/, '')] = `#${hex.slice(0, 6).toLowerCase()}`;
  }
  writeFileSync(
    join(root, BLESSING_COLORS_FILE),
    `# Generated by tools/blessing-colors.ts — average color of each blessing icon (placeholder)\n${stringify(colors)}`,
  );
  return Object.keys(colors).length;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  console.log(`✓ ${writeBlessingColors()} 个图标颜色 → ${BLESSING_COLORS_FILE}`);
}
