// Hero grid thumbnails and placeholder colors.
// - public/img/heroes/thumb/<id>.webp: 128px wide (q70) from the 256px portraits, for tiles and chips.
// - src/data/hero-colors.yaml: each portrait's average color, painted behind a tile until it loads.
// Usage: npm run thumbs [-- --force]   (needs ImageMagick: `magick`, or `convert` on ImageMagick 6)
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { stringify } from 'yaml';

const SRC = 'public/img/heroes';
const OUT = join(SRC, 'thumb');
const COLORS = 'src/data/hero-colors.yaml';
const force = process.argv.includes('--force');
const MAX_BYTES = 2560;

const im = (() => {
  for (const bin of ['magick', 'convert']) {
    try {
      execFileSync(bin, ['-version'], { stdio: 'ignore' });
      return bin;
    } catch {
      // try the next name
    }
  }
  throw new Error('需要 ImageMagick（magick 或 convert）');
})();

mkdirSync(OUT, { recursive: true });
const colors: Record<string, string> = {};
let made = 0;
for (const file of readdirSync(SRC).filter((f) => f.endsWith('.webp')).sort()) {
  const id = file.replace(/\.webp$/, '');
  const src = join(SRC, file);
  const dest = join(OUT, file);
  if (force || !existsSync(dest)) {
    // q70, stepping down for the few busy portraits that would exceed the 2.5 KB budget.
    for (const q of ['70', '62', '55']) {
      execFileSync(im, [src, '-resize', '128x', '-strip', '-quality', q, '-define', 'webp:method=6', dest]);
      if (statSync(dest).size <= MAX_BYTES) break;
    }
    made++;
  }
  // Average color: scale the whole portrait to one pixel.
  const hex = execFileSync(im, [src, '-scale', '1x1!', '-format', '%[hex:u.p{0,0}]', 'info:']).toString().trim();
  colors[id] = `#${hex.slice(0, 6).toLowerCase()}`;
}
writeFileSync(COLORS, `# Generated by tools/hero-thumbs.ts — average color of each hero portrait (tile placeholder)\n${stringify(colors)}`);
console.log(`✓ ${made} 张缩略图，${Object.keys(colors).length} 个颜色 → ${COLORS}`);
